- name: ensure required pkgs are installed
  sudo: yes
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
  - duplicity
  - cron
  when: ansible_os_family == "Debian"

- name: Creates local bin directory
  file: path={{ local_bin }} state=directory

- name: copy backup script into local bin directory
  copy: src={{ backup_script }} dest={{ local_bin }} mode=0744

- name: replace gpg key
  replace: dest="{{ local_bin }}/{{ backup_script }}" regexp='yourgpgkey' replace="{{ gpg_key }}"

- name: replace backup target
  replace: dest="{{ local_bin }}/{{ backup_script }}" regexp='yourtarget' replace="{{ backup_target }}"

- name: copy backup exclude list file into local bin directory
  copy: src={{ backup_exclude_list }} dest={{ local_bin }} 

- name: replace path
  replace: dest="{{ local_bin }}/{{ backup_exclude_list }}" regexp='^~' replace="/home/{{ user }}"

# Ensure exists a job that runs at 13 and 18.
- name: add cron entry for backup 
  cron: name="backup" user="{{ user }}" minute="0" hour="13,18" job="{{ local_bin }}/{{ backup_script }} > {{ local_bin }}/{{ backup_script }}.log"