#!/bin/bash

OUTPUT_DIR=~/Movies
SOURCE_DRIVE="/dev/sr0"
HANDBRAKE_PRESET="AppleTV 3"
EXTENSION="mkv"

function rip_dvd() {

        # Grab the DVD title
        DVD_TITLE=$(blkid -o value -s LABEL $SOURCE_DRIVE)
        # Replace spaces with underscores
        DVD_TITLE=${DVD_TITLE// /_}

        # Backup the DVD to out hard drive
        #dvdbackup -i $SOURCE_DRIVE -o $OUTPUT_DIR -M -n $DVD_TITLE

        # grep for the HandBrakeCLI process and get the PID
        HANDBRAKE_PID=`ps aux|grep H\[a\]ndBrakeCLI`
        set -- $HANDBRAKE_PID
        HANDBRAKE_PID=$2

        # Wait until our previous Handbrake job is done
        if [ -n "$HANDBRAKE_PID" ]
        then
                while [ -e /proc/$HANDBRAKE_PID ]; do sleep 1; done
        fi

        

        # And now we can start encoding
        HandBrakeCLI \
	    -i $SOURCE_DRIVE \
	    -o $OUTPUT_DIR/$DVD_TITLE.$EXTENSION \
	    --preset=$HANDBRAKE_PRESET \
	    --native-language ita \
	    --native-dub \
	    --audio 1,2,3 \
	    --aencoder copy:ac3 \
	    --audio-fallback ac3

	# HandBrake isn't ripping anything so we can pop out the disc
        eject $SOURCE_DRIVE

        # Clean up
        #rm -R $OUTPUT_DIR/$DVD_TITLE
}

rip_dvd
